// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX9zqGl1T61McPbgV4V3mf-nAlp3R3-jM',
    appId: '1:249534013238:web:61897623e2d83bbf151d97',
    messagingSenderId: '249534013238',
    projectId: 'fir-memo-app-82078',
    authDomain: 'fir-memo-app-82078.firebaseapp.com',
    storageBucket: 'fir-memo-app-82078.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhLTF4JyV7ZkLCqj5A-7sJ9NQ-EzEvw3c',
    appId: '1:249534013238:android:6e5f611ec8502dc5151d97',
    messagingSenderId: '249534013238',
    projectId: 'fir-memo-app-82078',
    storageBucket: 'fir-memo-app-82078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASgqWKwzZ69vkTCBODaKuCPMnOf7ELhr8',
    appId: '1:249534013238:ios:6a4d231bda28c8ad151d97',
    messagingSenderId: '249534013238',
    projectId: 'fir-memo-app-82078',
    storageBucket: 'fir-memo-app-82078.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASgqWKwzZ69vkTCBODaKuCPMnOf7ELhr8',
    appId: '1:249534013238:ios:93ce37fb1c5e7d94151d97',
    messagingSenderId: '249534013238',
    projectId: 'fir-memo-app-82078',
    storageBucket: 'fir-memo-app-82078.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
