
name: Remove Vercel Deployment for Closed PR


on:
  pull_request:
    types: [closed]
    branches:
      - develop

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  remove-deployment:
    if: github.event.pull_request.merged == true || github.event.pull_request.state == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install node-fetch

      - name: Remove Deployment
        run: node remove-deployment.js
        env:
          VERCEL_TOKEN: ${{ secrets.TOKEN }}
          BRANCH_NAME: ${{ github.head_ref }}
