name: Flutter Web Build and Deploy to Vercel

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web --web-renderer html

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        id: deploy
        run: echo "::set-output name=url::$(vercel deploy --prod --token ${{ secrets.TOKEN }} | grep -oP 'https://\S+\.vercel\.app')"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Comment Deploy URL
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const url = '${{ steps.deploy.outputs.url }}';
            const message = `Deployed URL: ${url}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
